### ISSUE TITLE
accessing http://ip:5000/browsingPage 

### ISSUE THREAD

**Issue by Willg3D** [bfforsythe/NotFlix#5]
accessing page causes odd output instead of redirect:
TypeError: /home/bfforsythe/Notflix/views/browsingPage.ejs:18
    16| <body>

    17| 

 >> 18|   <% if(user.accountType == "editor"){ %>

    19|     <button>

    20|         <a href="/upload">Upload</a>

    21|     </button>

Cannot read properties of undefined (reading 'accountType')
    at eval ("/home/bfforsythe/Notflix/views/browsingPage.ejs":15:16)
    at browsingPage (/home/bfforsythe/Notflix/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/home/bfforsythe/Notflix/node_modules/ejs/lib/ejs.js:274:36)
    at exports.renderFile [as engine] (/home/bfforsythe/Notflix/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/home/bfforsythe/Notflix/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/bfforsythe/Notflix/node_modules/express/lib/application.js:657:10)
    at Function.render (/home/bfforsythe/Notflix/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/home/bfforsythe/Notflix/node_modules/express/lib/response.js:1039:7)
    at /home/bfforsythe/Notflix/app.js:160:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by segallagher** [comment]
this has been fixed

**Comment by Willg3D** [comment]
I can confirm that the issue appears to be fixed. Now trying to bypass the login will result in being redirected back to the login.
You can close this issue.
